data-path="/data"
min-gas-price=0
genesis-file="/data/genesis.json"
permissions-nodes-config-file-enabled=true
nat-method="DOCKER"
host-allowlist=["*"]
metrics-enabled=true
metrics-host="0.0.0.0"
metrics-port=9545
metrics-protocol="PROMETHEUS"
metrics-category=["JVM","PROCESS","BLOCKCHAIN","ETHEREUM","EXECUTORS","NETWORK","PEERS","KVSTORE_ROCKSDB","KVSTORE_ROCKSDB_STATS","PRUNER","RPC","SYNCHRONIZER","TRANSACTION_POOL","STRATUM"]
Xdns-enabled=true
Xdns-update-enabled=true
rpc-http-enabled=true
rpc-ws-enabled=true
rpc-ws-host="0.0.0.0"
rpc-ws-api=["ADMIN","DEBUG","ETH","IBFT","NET","PERM","PLUGINS","QBFT","TRACE","TXPOOL","WEB3"]
rpc-http-api=["ADMIN","DEBUG","ETH","IBFT","NET","PERM","PLUGINS","QBFT","TRACE","TXPOOL","WEB3"]
rpc-http-cors-origins=["*"]
rpc-http-host="0.0.0.0"
Xp2p-peer-lower-bound=2
network-id=8658
sync-mode="FULL"
discovery-enabled=true
data-storage-format='FOREST'
pruning-enabled=false
